src/CloseButton.android.js
This PR fixed a crash on Android 4.4.2 (API level 19) when the picker modal popped up. Caused by calling [TouchableNativeFeedback.SelectableBackgroundBorderless][1] which is available on Android API level 21+.
Crash message:
```log
E/unknown:ViewManager(10320): Error while updating prop nativeBackgroundAndroid
E/unknown:ViewManager(10320): java.lang.reflect.InvocationTargetException
E/unknown:ViewManager(10320): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/unknown:ViewManager(10320): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/unknown:ViewManager(10320): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:77)
E/unknown:ViewManager(10320): 	at …
```
=> fixed calling unsupported method `TouchableNativeFeedback.SelectableBackgroundBorderless` for Android API level < 21

package.json, src/CountryPicker.js
Remove peer decencies of `react` and `react-native`.
Allow to customize flag button with static methods and children, example:
```
<CountryPicker
ref={ (c) => (this._countryPicker = c) }
onChange={(value)=> this.setState({country: value, cca2: value.cca2})}
cca2={this.state.cca2}
translation="fra"
closeable={ true }>
<View style={{ flexDirection: 'row' }}>
{ CountryPicker.renderFlag(this.state.cca2, { height: 26, width: 35 }) }
<Text style={ styles.phoneCountry }>
{ `+${this.state.country.callingCode}` }
</Text>
</View>
</CountryPicker>
```
=> Remove Peer dependencies and allow to customize flag button

package.json, src/CountryPicker.js, src/CountryPicker.style.js
- Fixes black background on the flag with RN 0.40 at iOS devices
- Adds support to render the component without an initial flag. Useful when you use it as a picker and the user has not selected a country yet.
- Increases package version
=> Various fixes explained in description

README.md, src/CountryPicker.js
I have a case where I need access to the country data before the modal renders to get user calling code (see updated README for example), and I don't want to import a whole separate json file.  Thus I added another `getAllCountries` export, so users can get access to the list of countries used.
I also added a prop `countryList` which is a cca2 code list that overrides the countries normally rendered.  Users can generate this list using the `getAllCountries` utility function.
=> Allow access to country data, and filtering of countries added

src/CountryPicker.js
I have a case that I need to remove Antarctica in the country list. So I add an exclude-country-list in props to make the picker filtering more easily.
For example, add excludeCountrise={['AQ']} in props, and Antarctica will not show in the list.
=> Add an exclude-country-list in props

package.json
Fix issue that component would show the error message: Unknown plugin "babel-plugin-add-module-exports" at the beginning
=> Fix error with react-native 0.43

src/CountryPicker.js
I need to display different country list as I've got different rate plans that support calling to different country. In the past when the user select a plan the country list did not change. This PR fixes this by listening to React lifecycle event `componentWillReceiveProps()` and update the `cca2List` and `dataSource` if needed.
=> update cca2List and dataSource state when receiving new props

src/CountryPicker.js
Currently when passing a translation property such as DE the country list gets translated but the sorting remains from the original EN translation (also the letters list clicking), this PR fixes this
=> Sort country list according to translation property

README.md, src/CountryPicker.js
Sometimes it is requirement to have a component like Uber's Login screen in which the country picker is disabled at first.
=> Disable/Enable the onPress event of Country Picker

src/CountryPicker.js
I've added a filterPlaceholderTextColor prop to the control as it isn't changeable in the standard style props.  I did it because I was using a dark background and the filterPlaceholder text wasn't visible.
=> Add filterPlaceholderTextColor prop

package.json, src/CountryPicker.js, src/emoji.js
This takes out the library, put it directly in this repo, and fixed the issues it had with React 16 prop-types.
=> Took out react-native-emoji dependency. It is tiny, and not up-to-date

src/CountryPicker.js
Introducing additional optional prop 'flagType' to enforce a certain flag type usage across platforms. Now the package forces you to use emoji flags on iOS and flat on Android.
This PR adds more versatility without changing the default behaviour.
flagType: 'flat' | 'emoji'
=> Additional optional prop 'flagType' to enforce a certain flag type usage across platforms

package.json
`babel-preset-react-native-stage-0` should not be in `dependencies`, it is in `devDependencies` already.
=> Remove babel-preset-react-native-stage-0 from dependencies

package.json, src/CountryPicker.d.ts, tsconfig.json, yarn.lock
Closes #127 .
I think this is how you add typings, seems to work when I import it via a `file://` dependency locally. But yeah I think all of these are accurate based on reading the docs and code as well as deriving much of the types from the source data.
=> add TypeScript typings for countrypicker

src/CountryPicker.js
Set propTypes.closeButtonImage in CountryPicker.js to the React Native ImageSource prop type (either number or {uri: ...} object)
=> Update prop type for closeButtonImage to fix #136

README.md, src/CountryPicker.js
An option to add the country name next to the flag in the view (not in the list view). This will provide a greater area for tapping as compared to the flag and some times it's easy to recognize the country by name instead of just flag.
=> Option to add country name next to flag

src/CountryPicker.js
I get this error when I create a CountryPicker with showCountryNameWithFlag but without init value.
=> Fix TypeError: undefined is not an object (evaluating 'country.name')

src/CountryPicker.js
If user press alphabetic which related county names outside of FlatList renderer, the scrollToIndex is not working. The issue is FlatList cannot scroll to locations outside the render window without specifying the getItemLayout prop.
=> Scroll to locations outside the render

src/CountryPicker.js
On Android, country picker could not show flags. This PR allows applying custom styles to the modal
=> [android] allow country picker modal reuse custom styles

src/CountryPicker.js, src/CountryPicker.style.js
Symptom: Android not rendering flags
Investigation: Images didn't render on iPhone either when turning off emoji mode
Cause: In RN 0.60+ an <Image> needs width and height set when loading from data: url scheme.
From RN Documentation: _"Note that for network and data images, you will need to manually specify the dimensions of your image!"_
Fix: Added "width" back in, it was commented out, added "contain" to the Image element just in case
I assume if some flags in there aren't 19 high it will look odd. But I tried other height and that messes up the design so left it at 19.
=> Fix for flag rendering on Android

README.md, src/CountryPicker.tsx, src/HeaderModal.tsx, src/index.tsx
In many use-cases (or at least in mine), I wanted to render a filter bar which would completely take up the entire `HeaderModal`. This PR makes the close button optional by adding a withCloseButton optional prop in the header which is set to true by default.
=> Make the close button optional in the header

src/index.tsx
I was getting the following error when using the library in a TypeScript project:
```
../../../../Repositories/react-native-country-picker-modal/lib/index.d.ts:37:26 - error TS1005: ';' expected.
37 export default namespace main {
~~~~
../../../../Repositories/react-native-country-picker-modal/lib/index.d.ts:37:31 - error TS1005: ';' expected.
37 export default namespace main {
~
```
Defining the default exported component as a const fixed the issue. This PR changes main type definition in `lib/index.d.ts` from
```ts
export default function main({ theme, translation, ...props }: Props): JSX.Element;
export default namespace main {
var defaultProps: {
onSelect: () => void;
withEmoji: boolean;
};
}
```
to 
```ts
declare const Main: {
({ theme, translation, ...props }: Props): JSX.Element; …
```
=> fix main component defaultProps types

src/CountryService.ts
Currently the filter is too fuzzy -- there are usually many unrelated results even if the user types an accurate country name. I found threshold 0.3 to be a fairly good choice.
Also added "cca2" into the search keys; otherwise, it would be a little confusing if searching "US" or "GB" returns no results.
=> Tuning fuzzy search

src/CountryPicker.tsx
On iOS13, there's a behavior to close the RN Modal with a swipe down gesture. In this case, the onDismiss method is called. Without onDismiss, the country picker will not open for the second time because its state will remain open.
=> added onDismiss method for iOS13 swipe-to-close behavior

src/CountryPicker.tsx
Fixed a bug where setCountries might get called on unmounted component
**Reproduce**
Load and unload fast the component, and then an warning is thrown.
_"Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function."_
=> Bugfix CountryPicker uncleared useEffect
